FROM ubuntu:18.04
# CMD["sleep", "4"]
# CMD sleep 4
ENTRYPOINT ["sleep"]
CMD ["2"]

# docker build -t ubuntu-sleeper .
# docker run ubuntu-sleeper
# docker run ubuntu-sleeper sleep 2

# docker run ubuntu-sleeper 5 (for entrypoint)
# docker run ubuntu-sleeper (missing operand error)
# docker run ubuntu-sleeper (default value run)